baseURL: http://example.org/
languageCode: en-us
title: My New Hugo Site

# Change the default theme to be use when building the site with Hugo
module:
  imports:
  - path: github.com/HEIGE-PCloud/DoIt

theme: github.com/HEIGE-PCloud/DoIt

params:
  # DoIt theme version
  version: 0.2.X

menu:
  main:
    - identifier: "posts"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre: ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post: ""
      name: "Posts"
      url: "/posts/"
      # title will be shown when you hover on this menu link
      title: ""
      weight: 1
    - identifier: "tags"
      pre: ""
      post: ""
      name: "Tags"
      url: "/tags/"
      title: ""
      weight: 2
    - identifier: "categories"
      pre: ""
      post: ""
      name: "Categories"
      url: "/categories/"
      title: ""
      weight: 3


# Markup related configuration in Hugo
markup:
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  highlight:
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false