baseURL: http://example.org/
languageCode: en-us
title: Senior Projects

# Change the default theme to be use when building the site with Hugo
module:
  imports:
  - path: github.com/HEIGE-PCloud/DoIt

minify:
  disableJSON: true

theme: github.com/HEIGE-PCloud/DoIt

params:
  # DoIt theme version
  version: 0.2.X
  paginate: 2
  page:
    toc:
      enable: true
    library:
      js:
        bootstrap: "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js"
      css:
        bootstrap: "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"

menu:
  main:
    - identifier: "offers"
      pre: ""
      post: ""
      name: "Offered Projects"
      url: "/offers/"
      title: ""
      weight: 1
    - identifier: "projects"
      # you can add extra information before the name (HTML format is supported), such as icons
      pre: ""
      # you can add extra information after the name (HTML format is supported), such as icons
      post: ""
      name: "Past Projects"
      url: "/projects/"
      # title will be shown when you hover on this menu link
      title: ""
      weight: 2


# Markup related configuration in Hugo
markup:
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  highlight:
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false