baseURL: http://localhost:1313/
languageCode: en-us
title: Senior Projects

module:
  mounts:
  - source: static/home
    target: assets/home
  - source: static
    target: static
  - source: assets
    target: assets

build:
  noJSConfigInAssets: true

timeout: 300s # Image processing may take some time, default was 30s

minify:
  disableJSON: true

summaryLength: 1

params:
  year: "2022"
  semester: "spring"

taxonomies:
  advisors: advisors

RemovePathAccents: true

menu:
  main:
    - identifier: "offers"
      name: "Offered Projects"
      url: "/offers/"
      title: ""
      weight: 1
    - identifier: "ongoing"
      name: "Ongoing Projects"
      url: "/ongoing/"
      title: ""
      weight: 2
    - identifier: "semesters"
      name: "Past Projects"
      url: "/semesters/"
      title: ""
      weight: 3
    - identifier: "about"
      name: "About"
      url: "/about/"
      title: ""
      weight: 1
    - identifier: "awards"
      name: "Awards"
      url: "/awards/"
      title: ""
      weight: 4

outputs:
  home:
    - HTML
    - JSON