languageCode: en-us
title: Senior Projects

module:
  vendor: true
  mounts:
  - source: node_modules/lightgallery/fonts
    target: static/fonts
  - source: node_modules/lightgallery/images
    target: static/images
  imports:
  - path: github.com/gohugoio/hugo-mod-bootstrap-scss/v5

minify:
  disableJSON: true

summaryLength: 1

params:
  year: "2022"
  semester: "spring"

taxonomies:
  advisors: advisors

RemovePathAccents: true

menu:
  main:
    - identifier: "offers"
      name: "Offered Projects"
      url: "/offers/"
      title: ""
      weight: 1
    - identifier: "ongoing"
      name: "Ongoing Projects"
      url: "/ongoing/"
      title: ""
      weight: 2
    - identifier: "semesters"
      name: "Past Projects"
      url: "/semesters/"
      title: ""
      weight: 3
    - identifier: "about"
      name: "About"
      url: "/about/"
      title: ""
      weight: 1
    - identifier: "awards"
      name: "Awards"
      url: "/awards/"
      title: ""
      weight: 4

outputs:
  home:
    - HTML
    - JSON

# Markup related configuration in Hugo
markup:
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  highlight:
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses: false