backend:
  # name: git-gateway
  name: github
  branch: main
  repo: bouncmpe/seniorprojects
  site_domain: bouncmpe-seniorprojects.netlify.app

search: false
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: assets/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "offer" # Used in routes, e.g., /admin/collections/blog
    label: "Offer" # Used in the UI
    folder: "content/offers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
    # will probably need to sort these out.
      - {label: "Title", name: "title", widget: "string", default: "title"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Advisors", name: "advisors", widget: "list"}
      - {label: "Authors", name: "authors", widget: "list"}
      - {label: "Type", name: "type", default: "posts"}
      - {label: "Body", name: body, widget: markdown}

