backend:
  # name: git-gateway
  name: github
  branch: main
  repo: bouncmpe/seniorprojects
  base_url: http://157.245.22.69:3000

search: false
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: static/images/uploads # Media files will be stored in the repo under static/images/uploads
public_folder: /images/uploads # The src attribute for uploaded media will begin with /images/uploads
slug:
  encoding: "ascii"
  clean_accents: true

collections:
  - name: "offer" # Used in routes, e.g., /admin/collections/blog
    label: "Offer" # Used in the UI
    folder: "content/offers" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      # will probably need to sort these out.
      - { label: "Title", name: "title", widget: "string", default: "title" }
      - { label: "Date", name: "date", widget: "datetime" }
      - {
          label: "Advisor",
          name: "advisors",
          widget: "select",
          multiple: true,
          min:1,
          options:
            [
              "A. C. Cem Say",
              "Alper Şen",
              "Arda Yurdakul",
              "Arzucan Özgür",
              "Atay Özgövde",
              "Berk Gökberk",
              "Can Özturan",
              "Cem Ersoy",
              "Doğan Ulus",
              "Emre Uğur",
              "Eren Soyak",
              "Fatih Alagöz",
              "Fatma Başak Aydemir",
              "Fikret Gürgen",
              "H. Birkan Yılmaz",
              "İnci Meliha Baytaş",
              "Lale Akarun",
              "Mehmet Turan",
              "Özlem Durmaz İncel",
              "Pınar Yanardağ",
              "Suzan Üsküdarlı",
              "Tuna Tuğcu",
              "Tunga Güngör",
            ],
        }
      - {
          label: "Co-Advisor",
          name: "co_advisors",
          widget: "string",
          required: false,
        }
      - { label: "Body", name: "body", widget: markdown }
      - { label: "Tags", name: "tags", widget: "list", required: false }
